
.PHONY: build

build:
	go build ./...
	go build ./cmd/pfTraceGenerator
	go build ./cmd/pfToggle
	go build ./cmd/buildAllowList
	go build ./cmd/pfExecWriteSeq
	go build ./cmd/detectExecPages
	go build ./cmd/pfOSSLAttackECDH/
	go build ./cmd/pfOSSLRecoverECDHKey
	go build ./cmd/test
	go build ./cmd/pfBatchTraceGenerator
	go build ./cmd/pfOSSHAttackEdDSA/
	go build ./cmd/jsonToPlain
	go build ./cmd/pfOSSHRecoverEdDSAKey